### ISSUE TITLE
Add Rest endpoint to create tutorial groups

### ISSUE THREAD

**Issue by djwessel** [djwessel/ASEProject#8]
Add endpoint through Restlet to create tutorial groups to be stored in Objectify. Information required includes class id and group name/number.

**Comment by anahitH** [comment]
Implemented this issue in GroupResource class.

**Comment by djwessel** [comment]
I'm not sure if this is totally correct. I tried testing the API and it wasn't recognizing the courseID and groupID from the URL path.

```@Get
        public Group retrieve(String courseID, String groupID)
        {
                Group group = retrieveGroup(courseID, groupID);
                if (group == null) {
                        throw new RuntimeException(noGroupMsg);
                }
                return group;
        }
```
You need to get the attributes using something like this
```
courseID = getAttribute("course_id");
groupID = getAttribute("group_name");
```

Otherwise the courseID and groupID end up being null.
